/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    events: Event;
    'journal-posts': JournalPost;
    recognitions: Recognition;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    recognitions: RecognitionsSelect<false> | RecognitionsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    homepage: Homepage;
    chef: Chef;
    'page-media': PageMedia;
    'site-settings': SiteSetting;
    navigation: Navigation;
    'menu-page': MenuPage;
    'about-page': AboutPage;
    'experience-page': ExperiencePage;
    'occasions-page': OccasionsPage;
    'visit-page': VisitPage;
    'recognition-page': RecognitionPage;
    'events-page': EventsPage;
    'journal-page': JournalPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    chef: ChefSelect<false> | ChefSelect<true>;
    'page-media': PageMediaSelect<false> | PageMediaSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'menu-page': MenuPageSelect<false> | MenuPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'experience-page': ExperiencePageSelect<false> | ExperiencePageSelect<true>;
    'occasions-page': OccasionsPageSelect<false> | OccasionsPageSelect<true>;
    'visit-page': VisitPageSelect<false> | VisitPageSelect<true>;
    'recognition-page': RecognitionPageSelect<false> | RecognitionPageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Internal migration identity key (used for deterministic seeding).
   */
  sourceKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  name: string;
  /**
   * Optional editorial note displayed beneath the category title on the website.
   */
  sectionNote?: string | null;
  menuType: 'food' | 'beverage';
  sortOrder: number;
  isActive?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  description?: string | null;
  priceLabel?: string | null;
  portion?: string | null;
  priceVariants?:
    | {
        portion?: string | null;
        label?: string | null;
        priceLabel: string;
        id?: string | null;
      }[]
    | null;
  subhead?: string | null;
  subheadNote?: string | null;
  additionalNotes?:
    | {
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dish image rendered when selected as a Homepage Signature Dish.
   */
  image?: (number | null) | Media;
  category: number | MenuCategory;
  isIntroBlock?: boolean | null;
  featured?: boolean | null;
  signature?: boolean | null;
  isAvailable?: boolean | null;
  sortOrder?: number | null;
  /**
   * Internal immutable migration identity
   */
  sourceKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Event hero cover image displayed at the top of the event detail page.
   */
  coverImage: number | Media;
  /**
   * Event category/kicker displayed above the title on the detail page.
   */
  eyebrow?: string | null;
  title: string;
  startDateTime: string;
  endDateTime?: string | null;
  priceLabel?: string | null;
  /**
   * Main body copy for the event detail page.
   */
  fullDescription?: string | null;
  /**
   * Listing & Card Content: Summary copy displayed on event cards in listings.
   */
  shortDescription?: string | null;
  /**
   * Listing & Card Content: Highlight this event on listing cards.
   */
  featured?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  /**
   * Article category displayed at the top of the article header.
   */
  category: string;
  title: string;
  publishDate: string;
  authorLabel?: string | null;
  /**
   * Single main editorial image positioned after header and before body content.
   */
  coverImage: number | Media;
  /**
   * Editorial caption rendered directly beneath the main cover image.
   */
  imageCaption?: string | null;
  /**
   * Introduction / Lead paragraph displayed before the article body.
   */
  excerpt?: string | null;
  /**
   * Main article body content (textual rich content only; no embedded images).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognitions".
 */
export interface Recognition {
  id: number;
  /**
   * Year or date of recognition (e.g. "2024").
   */
  year: string;
  /**
   * Name of the awarding body or publication.
   */
  awardingBody: string;
  /**
   * Title of the recognition or award.
   */
  title: string;
  scope: 'restaurant' | 'chef';
  /**
   * Single main editorial image positioned after header and before body content.
   */
  coverImage?: (number | null) | Media;
  /**
   * Editorial caption rendered directly beneath the main cover image.
   */
  imageCaption?: string | null;
  /**
   * Introduction / Lead paragraph displayed before the article body.
   */
  excerpt?: string | null;
  /**
   * Main recognition body content (textual rich content only; no embedded images).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Unique URL slug for recognition detail (e.g. "michelin-guide-2024").
   */
  slug: string;
  contentStatus: 'verified' | 'demo' | 'needs-confirmation';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * The exact quote text from the guest.
   */
  quote: string;
  /**
   * Name or public identifier of the guest (e.g. John D., @foodie_surabaya).
   */
  attribution?: string | null;
  sourceType: 'direct' | 'google' | 'instagram' | 'press' | 'other';
  /**
   * Display label or context for the source (e.g. Google Review, Table 4 Feedback).
   */
  sourceLabel?: string | null;
  /**
   * Direct link to the public review or post where applicable.
   */
  sourceUrl?: string | null;
  /**
   * Only verified reviews can be selected for public display on the Homepage.
   */
  verificationStatus: 'unverified' | 'verified';
  /**
   * Set to inactive to temporarily withdraw this review without deleting it.
   */
  isActive?: boolean | null;
  /**
   * Editorial or provenance notes for internal admin use only.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'recognitions';
        value: number | Recognition;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourceKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  sectionNote?: T;
  menuType?: T;
  sortOrder?: T;
  isActive?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  priceLabel?: T;
  portion?: T;
  priceVariants?:
    | T
    | {
        portion?: T;
        label?: T;
        priceLabel?: T;
        id?: T;
      };
  subhead?: T;
  subheadNote?: T;
  additionalNotes?:
    | T
    | {
        note?: T;
        id?: T;
      };
  image?: T;
  category?: T;
  isIntroBlock?: T;
  featured?: T;
  signature?: T;
  isAvailable?: T;
  sortOrder?: T;
  sourceKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  coverImage?: T;
  eyebrow?: T;
  title?: T;
  startDateTime?: T;
  endDateTime?: T;
  priceLabel?: T;
  fullDescription?: T;
  shortDescription?: T;
  featured?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  publishDate?: T;
  authorLabel?: T;
  coverImage?: T;
  imageCaption?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognitions_select".
 */
export interface RecognitionsSelect<T extends boolean = true> {
  year?: T;
  awardingBody?: T;
  title?: T;
  scope?: T;
  coverImage?: T;
  imageCaption?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  slug?: T;
  contentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  sourceType?: T;
  sourceLabel?: T;
  sourceUrl?: T;
  verificationStatus?: T;
  isActive?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    headline?: string | null;
    kicker?: string | null;
    support?: string | null;
    location?: string | null;
    ctaPrimary?: string | null;
    ctaSecondary?: string | null;
    ctaLabel?: string | null;
    image: number | Media;
  };
  positioning?: {
    text?: string | null;
    dietary?: string | null;
  };
  /**
   * Controls the four category/course labels and background images in the Homepage Cuisine/Menu teaser. This is separate from Signature Dishes.
   */
  cuisineTeaser: {
    item01: {
      label: string;
      image: number | Media;
    };
    item02: {
      label: string;
      image: number | Media;
    };
    item03: {
      label: string;
      image: number | Media;
    };
    item04: {
      label: string;
      image: number | Media;
    };
  };
  /**
   * Controls the four individual dish cards in the Signature Dishes carousel. This is separate from the Cuisine / Menu Teaser section.
   */
  signatureDishes: {
    title?: string | null;
    /**
     * Select exactly 4 dishes for the Homepage. Drag to control display order.
     */
    items: (number | MenuItem)[];
  };
  space: {
    title?: string | null;
    text?: string | null;
    ctaLabel?: string | null;
    imagePrimary: number | Media;
    imageSecondary: number | Media;
  };
  chefPreview?: {
    text?: string | null;
    ctaLabel?: string | null;
  };
  eventsIntro?: {
    ctaLabel?: string | null;
  };
  /**
   * Select verified guest reviews shown in the Homepage carousel. Review order here controls carousel order.
   */
  reviews?: {
    kicker?: string | null;
    /**
     * Select verified and active guest reviews. Drag to control display order.
     */
    items?: (number | Review)[] | null;
  };
  journalIntro?: {
    title?: string | null;
    ctaLabel?: string | null;
  };
  visitIntro?: {
    title?: string | null;
    locationHeading?: string | null;
    servicesHeading?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chef".
 */
export interface Chef {
  id: number;
  /**
   * Portrait photo featured on the Chef page with grayscale-to-color reveal.
   */
  portrait: number | Media;
  name: string;
  role?: string | null;
  biography?: string | null;
  quote?: string | null;
  /**
   * Supporting video used for the Homepage Chef Preview media blob.
   */
  videoFile: number | Media;
  /**
   * Poster image for the supporting video.
   */
  videoPoster: number | Media;
  /**
   * Short editorial description used for Chef page metadata / preview context.
   */
  previewText?: string | null;
  /**
   * POTENTIALLY DEAD: Homepage reads homepage.chefPreview.ctaLabel. Preserved for backward compatibility.
   */
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-media".
 */
export interface PageMedia {
  id: number;
  menu: {
    /**
     * Hero / Featured Food Image (Large banner shown when Food menu is selected).
     */
    foodImage: number | Media;
    /**
     * Hero / Featured Beverage Image (Large banner shown when Beverage menu is selected).
     */
    beverageImage: number | Media;
  };
  experience: {
    heroImage: number | Media;
    morningImage: number | Media;
    eveningImage: number | Media;
    detailsImage: number | Media;
    /**
     * Select the image shown in Material slot 01 (Transitional color swatch shown if unselected).
     */
    materialImage01?: (number | null) | Media;
    /**
     * Select the image shown in Material slot 02 (Transitional color swatch shown if unselected).
     */
    materialImage02?: (number | null) | Media;
    /**
     * Select the image shown in Material slot 03 (Transitional color swatch shown if unselected).
     */
    materialImage03?: (number | null) | Media;
    /**
     * Select the image shown in Material slot 04 (Transitional color swatch shown if unselected).
     */
    materialImage04?: (number | null) | Media;
  };
  occasions: {
    heroImage: number | Media;
    privateDiningImage: number | Media;
    weddingImage: number | Media;
    birthdayImage: number | Media;
    brandMondialImage: number | Media;
    brandFrankCoImage: number | Media;
    brandMaharvaImage: number | Media;
  };
  about: {
    originImage: number | Media;
    philosophyImage: number | Media;
    architectureImage: number | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  restaurantName: string;
  phone?: string | null;
  whatsappNumber?: string | null;
  email?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  fullAddress?: string | null;
  /**
   * Presentation text for footer/location badges; does not replace fullAddress.
   */
  locationLabel?: string | null;
  mapUrl?: string | null;
  dietaryPolicy?: string | null;
  services?: 'dine-in'[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page".
 */
export interface MenuPage {
  id: number;
  title: string;
  philosophy?: string | null;
  taxServiceFootnote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    headline: string;
    subtitle: string;
  };
  origin: {
    title: string;
    body1: string;
    body2: string;
  };
  philosophy: {
    title: string;
    body1: string;
    dietaryPrefix: string;
    dietarySuffix: string;
  };
  architecture: {
    title: string;
    body1: string;
    body2: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-page".
 */
export interface ExperiencePage {
  id: number;
  hero: {
    kicker: string;
    headline: string;
  };
  quote: string;
  dayToNight: {
    heading: string;
    subtitle: string;
    morningHeading: string;
    morningDescription: string;
    transitionQuote: string;
    eveningHeading: string;
    eveningDescription: string;
  };
  materials: {
    heading: string;
    body1: string;
    body2: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions-page".
 */
export interface OccasionsPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
  };
  privateDining: {
    title: string;
    description: string;
    feature1: string;
    feature2: string;
    feature3: string;
  };
  wedding: {
    title: string;
    description: string;
    feature1: string;
    feature2: string;
    feature3: string;
  };
  birthday: {
    title: string;
    description: string;
    feature1: string;
    feature2: string;
    feature3: string;
  };
  brandExclusives: {
    heading: string;
    description: string;
  };
  brandEvents: {
    mondial: {
      brand: string;
      title: string;
    };
    frankCo: {
      brand: string;
      title: string;
    };
    maharva: {
      brand: string;
      title: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-page".
 */
export interface VisitPage {
  id: number;
  title: string;
  contactHeading: string;
  reservationsHeading: string;
  reservationsNote: string;
  dietaryPolicy: {
    heading: string;
    description: string;
  };
  dressCodePolicy: {
    heading: string;
    description: string;
  };
  parkingPolicy: {
    heading: string;
    description: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognition-page".
 */
export interface RecognitionPage {
  id: number;
  kicker?: string | null;
  title: string;
  subtitle: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  title: string;
  subtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  title: string;
  subtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        kicker?: T;
        support?: T;
        location?: T;
        ctaPrimary?: T;
        ctaSecondary?: T;
        ctaLabel?: T;
        image?: T;
      };
  positioning?:
    | T
    | {
        text?: T;
        dietary?: T;
      };
  cuisineTeaser?:
    | T
    | {
        item01?:
          | T
          | {
              label?: T;
              image?: T;
            };
        item02?:
          | T
          | {
              label?: T;
              image?: T;
            };
        item03?:
          | T
          | {
              label?: T;
              image?: T;
            };
        item04?:
          | T
          | {
              label?: T;
              image?: T;
            };
      };
  signatureDishes?:
    | T
    | {
        title?: T;
        items?: T;
      };
  space?:
    | T
    | {
        title?: T;
        text?: T;
        ctaLabel?: T;
        imagePrimary?: T;
        imageSecondary?: T;
      };
  chefPreview?:
    | T
    | {
        text?: T;
        ctaLabel?: T;
      };
  eventsIntro?:
    | T
    | {
        ctaLabel?: T;
      };
  reviews?:
    | T
    | {
        kicker?: T;
        items?: T;
      };
  journalIntro?:
    | T
    | {
        title?: T;
        ctaLabel?: T;
      };
  visitIntro?:
    | T
    | {
        title?: T;
        locationHeading?: T;
        servicesHeading?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chef_select".
 */
export interface ChefSelect<T extends boolean = true> {
  portrait?: T;
  name?: T;
  role?: T;
  biography?: T;
  quote?: T;
  videoFile?: T;
  videoPoster?: T;
  previewText?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-media_select".
 */
export interface PageMediaSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        foodImage?: T;
        beverageImage?: T;
      };
  experience?:
    | T
    | {
        heroImage?: T;
        morningImage?: T;
        eveningImage?: T;
        detailsImage?: T;
        materialImage01?: T;
        materialImage02?: T;
        materialImage03?: T;
        materialImage04?: T;
      };
  occasions?:
    | T
    | {
        heroImage?: T;
        privateDiningImage?: T;
        weddingImage?: T;
        birthdayImage?: T;
        brandMondialImage?: T;
        brandFrankCoImage?: T;
        brandMaharvaImage?: T;
      };
  about?:
    | T
    | {
        originImage?: T;
        philosophyImage?: T;
        architectureImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  restaurantName?: T;
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  fullAddress?: T;
  locationLabel?: T;
  mapUrl?: T;
  dietaryPolicy?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page_select".
 */
export interface MenuPageSelect<T extends boolean = true> {
  title?: T;
  philosophy?: T;
  taxServiceFootnote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subtitle?: T;
      };
  origin?:
    | T
    | {
        title?: T;
        body1?: T;
        body2?: T;
      };
  philosophy?:
    | T
    | {
        title?: T;
        body1?: T;
        dietaryPrefix?: T;
        dietarySuffix?: T;
      };
  architecture?:
    | T
    | {
        title?: T;
        body1?: T;
        body2?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-page_select".
 */
export interface ExperiencePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        headline?: T;
      };
  quote?: T;
  dayToNight?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        morningHeading?: T;
        morningDescription?: T;
        transitionQuote?: T;
        eveningHeading?: T;
        eveningDescription?: T;
      };
  materials?:
    | T
    | {
        heading?: T;
        body1?: T;
        body2?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions-page_select".
 */
export interface OccasionsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  privateDining?:
    | T
    | {
        title?: T;
        description?: T;
        feature1?: T;
        feature2?: T;
        feature3?: T;
      };
  wedding?:
    | T
    | {
        title?: T;
        description?: T;
        feature1?: T;
        feature2?: T;
        feature3?: T;
      };
  birthday?:
    | T
    | {
        title?: T;
        description?: T;
        feature1?: T;
        feature2?: T;
        feature3?: T;
      };
  brandExclusives?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  brandEvents?:
    | T
    | {
        mondial?:
          | T
          | {
              brand?: T;
              title?: T;
            };
        frankCo?:
          | T
          | {
              brand?: T;
              title?: T;
            };
        maharva?:
          | T
          | {
              brand?: T;
              title?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-page_select".
 */
export interface VisitPageSelect<T extends boolean = true> {
  title?: T;
  contactHeading?: T;
  reservationsHeading?: T;
  reservationsNote?: T;
  dietaryPolicy?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  dressCodePolicy?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  parkingPolicy?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognition-page_select".
 */
export interface RecognitionPageSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  subtitle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}